root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/api ./cmd/api/main.go"
bin = "./tmp/api"
full_bin = "./tmp/api"
include_ext = ["go", "env"]
exclude_dir = ["tmp", "vendor", ".git"]
delay = 500
stop_on_error = true

[log]
time = true